---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: databases
spec:
  encryptedData:
    password: AgCFTr5ldpjWc2RtzLu4jIMVbBrg7x11xNiZgGGEjLsyW0lswvMGfj9JHx+6sXpZtEaU3aS7dKw6w7xOtXpdh7sscLCcNXvaAAo5iE6j40fK805l0MCyvkWOvVIVFrDZFB2XM5bO4qj0Pn1eg8/1isS9B3w2RnyJRZ7juFC/geUbTgEew9bOowUpFmyIauIIuQfMYfzlHbiRYOQ6yhTKo7VnBHd90XLzsT3Jd5aQTnzlgfmMbz+0MNt4XtgBpKjv0FPP4xiXCKHV5ra7AgMQF4P4eRmho+lMmjMdPejkRoQwXPiTCO6F8uECxlNrOCUUNNsONNN0PNh9hpUnyy8xCNc9mNW3kgM1wqOR9ZrDQD55BR9jfTcdphliHjbnppSppj+ZnYw9IdabzUD4X65Qd/N4kDzGHsP0yio4Pm2Jeg+NwhbeDKNsEwAsOayA9d06wO6HxYZKCHSr+a6REdPG44552eCeXKPY90FILG/B1goItSbECL35RVzJITPB5s8UjSt49Dy/o9xdFiIJVoni//1weLRz8oDGQ/h465Zq0wEuujl6P5fMbiKuyYPgcNqDYwVhI7025gbprQALEJlSLk/Vwqh7nY44bKrhYqEAZWJtMbaoixiqSksDq3/KcWunZ8IdgD0ht4gYwB3NkIxDM9+s9Wap59fibTVUD/dbPv/WCNxWSHYWQibCKmgLcb30ubgxJA2aZ1sInj0+VsXgXCvaKxa3Gw==
  template:
    metadata:
      name: pgadmin-secret
      namespace: databases
